#!/bin/sh

rix.rvm.install.rails()
{
  log step "install rails"
  printf "\n"
  if gem install rails $@ 2>&1 | tee $logs/install_rails | awk '{printf "."; flush}'
  then
    log step success
  else
    log step failed
  fi
}

rix.rvm.install.ruby()
{
  log step "install ruby - $1"
  printf "\n"
  if rvm install $@ 2>&1 | tee $logs/install_ruby-$1 | awk '{printf "."; fflush}'
  then
    log step success
  else
    log step failed
  fi
}

rix.rvm.default.ruby()
{
  log step "alias default ruby - $1"
  local _name
  if rvm alias $1 default >/dev/null &&
    [[ -r /usr/local/rvm/environments/default ]]
  then
    log step success
  else
    log step failed
  fi
  log step "use default ruby"
  if source /usr/local/rvm/environments/default
  then
    log step success
  else
    log step failed
  fi
}

rix.rvm.install()
{
  typeset __status
  log step "install rvm"
  pushd $rvm_local_path >/dev/null
  if bash -e ./install >$logs/install_rvm 2>&1 &&
    [[ -d /usr/local/rvm/bin ]]
  then
    __status=0
    PATH=/usr/local/rvm/bin:$PATH
    log step success
    popd >/dev/null
  else
    log step failed
    popd >/dev/null
    return 1
  fi

  local _rvm_path
  if [[ -n "$SUDO_USER" ]]
  then
    _rvm_path=$( awk -F : '/^'"$SUDO_USER"':/ { print $6 }' < /etc/passwd )
    if [[ -d "${_rvm_path}/.rvm" ]]
    then
      _rvm_path="${_rvm_path}/.rvm"
    else
      _rvm_path=""
    fi
  fi
  if [[ -z "${_rvm_path}" && -d /usr/local/rvm.$timestamp ]]
  then
    _rvm_path=/usr/local/rvm.$timestamp
  fi
  if [[ -d ${_rvm_path}/archives/ ]]
  then
    log step "link archives to ${_rvm_path}/archives"
    rm -rf /usr/local/rvm/archives/
    ln -s ${_rvm_path}/archives/ /usr/local/rvm/archives
    log step success
  fi
}
