#!/bin/sh

rix.rvm.install.rails()
{
  log step "install rails"
  printf "\n"
  if gem install rails $@ 2>&1 | tee $logs/install_rails | log dotted
  then
    log step success
  else
    log step failed
  fi
}

rix.rvm.install.ruby()
{
  log step "install ruby - $1"
  printf "\n"
  if
    LDFLAGS="-L/opt/sm/pkg/active/lib" \
    CFLAGS="-I/opt/sm/pkg/active/include" \
    CPATH="/opt/sm/pkg/active/include" \
    rvm install $@ 2>&1 | tee $logs/install_ruby-$1 | log dotted
  then
    log step success
  else
    log step failed
  fi
}

rix.rvm.default.ruby()
{
  local _name
  _name=$(/usr/local/rvm/bin/rvm $1 do rvm current)
  log step "alias default ruby - $_name"
  if rvm alias create default $_name && #>/dev/null &&
    [[ -L /usr/local/rvm/environments/default ]]
  then
    log step success
  else
    log step failed
    return 1
  fi
  log step "use default ruby"
  if builtin source "/usr/local/rvm/environments/default"
  then
    log step success
  else
    log step failed
    return 1
  fi
}

rix.rvm.install()
{
  typeset __status
  log step "install rvm"
  pushd $rvm_local_path >/dev/null
  if bash -e ./install >$logs/install_rvm 2>&1 &&
    [[ -d /usr/local/rvm/bin ]]
  then
    __status=0
    PATH=/usr/local/rvm/bin:$PATH
    log step success
    popd >/dev/null
  else
    log step failed
    popd >/dev/null
    return 1
  fi

  local _rvm_path
  if [[ -n "$SUDO_USER" ]]
  then
    _rvm_path=$( awk -F : '/^'"$SUDO_USER"':/ { print $6 }' < /etc/passwd )
    if [[ -d "${_rvm_path}/.rvm" ]]
    then
      _rvm_path="${_rvm_path}/.rvm"
    else
      _rvm_path=""
    fi
  fi
  if [[ -z "${_rvm_path}" && -d /usr/local/rvm.$timestamp ]]
  then
    _rvm_path=/usr/local/rvm.$timestamp
  fi
  if [[ -d ${_rvm_path}/archives/ ]]
  then
    log step "link archives to ${_rvm_path}/archives"
    rm -rf /usr/local/rvm/archives/
    ln -s ${_rvm_path}/archives/ /usr/local/rvm/archives
    log step success
  fi
}
