#!/bin/sh

rix_initialize()
{
  rix.start
}

rix.start()
{
  trace_filter action
  log "Rails Installer uniX - preparation script - start"
  log_step "backup sm" rix.old_install.backup
  rix.sm.install #it shows its own steps
  log_step "restore sm" rix.old_install.restore
  log "Rails Installer uniX - preparation script - finished"
}

rix.sm.install()
{
  export install_path=/opt/sm
  install_sm
}

rix.old_install.backup()
{
  if paths exist /opt/sm
  then
    paths remove /opt/sm.$timestamp
    paths move from /opt/sm to /opt/sm.$timestamp
  fi
  if paths exist /usr/local/rvm
  then
    paths remove /usr/local/rvm.$timestamp
    paths move from /usr/local/rvm to /usr/local/rvm.$timestamp
  fi
}

rix.old_install.restore()
{
  if paths exist /opt/sm.$timestamp
  then
    paths remove /opt/sm
    paths move from /opt/sm.$timestamp to /opt/sm
  fi
  if paths exist /usr/local/rvm.$timestamp
  then
    paths remove /usr/local/rvm
    paths move from /usr/local/rvm.$timestamp to /usr/local/rvm
  fi
}
